### ISSUE TITLE
Bookmarking for integrate() does not work

### ISSUE THREAD

**Issue by joefresna** [DiODeProject/MuMoT#273] opened 2019-02-18 18:35 UTC
The bookmarking functionality for `integrate()` does not seem to work...
It gives the error:
`TypeError: _print_standalone_view_cmd() takes from 1 to 2 positional arguments but 3 were given`

**Comment by jarmarshall** [comment] 2019-02-18 19:15
Presumed to be a duplicate of issue #255

**Closed by jarmarshall** 2019-02-18 19:15 UTC
Labels: bug
