### ISSUE TITLE
Non-deterministic error in noiseCorrelations()

### ISSUE THREAD

**Issue by jarmarshall** [DiODeProject/MuMoT#235] opened 2018-12-07 17:15 UTC
`noiseCorrelations()`(cell 7 in `MuMoTtest.ipynb`) exhibits a non-deterministic runtime error `IndexError: list index out of range` within `_numericSol2ndOrdMoment()`

Restarting the notebook can clear this.

This may cause issues with Travis continuous integration

**Comment by tbose1** [comment] 2019-02-15 20:14
This error occurs only occasionally and can often not be reproduced when the same parameter values are used. When the error occurs or not occurs the computation running in the background seems to give the same (correct) results in both cases. Therefore, it is hard to see what the origin is. I made several changes in the code to improve code structure and error messages. In addition, I implemented a check if the list index error occurs: if it occurs then a warning message is printed to the screen saying that the calculation was unsuccessful, no figure is generated in this case (`None` is returned internally) and advice is given to change values on initial sliders. The error seems to be sensible to those values. All changes are made via 4f87aa74fb3969a3f4ceeb2f28cd17a949e8a59f. As this prevents the error message and enables the continued execution of notebooks I close this issue.

**Closed by tbose1** 2019-02-15 20:14 UTC
Labels: bug
